import { PrismaClient, Prisma, WalletCategory } from '@prisma/client';

const prisma = new PrismaClient();

async function seedPrices() {
  const prices: {
    itemCode: string;
    category: WalletCategory;
    name: string;
    description: string;
    creditsPerUnit: number;
    unitType: string;
    minCredits?: number;
    maxCredits?: number;
    metadata?: Prisma.InputJsonValue;
  }[] = [
    // ═══════════════════════════════════════════════════
    // TEXT MODELS (sorted by credits/cost)
    // ═══════════════════════════════════════════════════
    {
      itemCode: 'TEXT_FAST',
      category: 'TEXT',
      name: 'Fast AI',
      description: 'Fast open-source model via Groq (Llama 3.3 70B, ~$0.0003/req)',
      creditsPerUnit: 1,
      unitType: '1_request',
      metadata: { provider: 'groq', model: 'llama-3.3-70b-versatile', baseCost: 0.0003 },
    },
    {
      itemCode: 'TEXT_GEMINI_FLASH',
      category: 'TEXT',
      name: 'Gemini Flash',
      description: 'Google Gemini 2.5 Flash — fast and cheap (~$0.0002/req)',
      creditsPerUnit: 1,
      unitType: '1_request',
      metadata: { provider: 'google', model: 'gemini-2.5-flash', baseCost: 0.0002 },
    },
    {
      itemCode: 'TEXT_GPT4O_MINI',
      category: 'TEXT',
      name: 'GPT-4o Mini',
      description: 'Fast and efficient OpenAI model (~$0.0002/req)',
      creditsPerUnit: 2,
      unitType: '1_request',
      metadata: { provider: 'openai', model: 'gpt-4o-mini', baseCost: 0.0002 },
    },
    {
      itemCode: 'TEXT_GROK',
      category: 'TEXT',
      name: 'Grok',
      description: 'xAI Grok 3 Mini (~$0.0002/req)',
      creditsPerUnit: 2,
      unitType: '1_request',
      metadata: { provider: 'xai', model: 'grok-3-mini', baseCost: 0.0002 },
    },
    {
      itemCode: 'TEXT_LLAMA4_MAVERICK',
      category: 'TEXT',
      name: 'Llama 4 Maverick',
      description: 'Latest Meta Llama 4 model (~$0.0004/req)',
      creditsPerUnit: 2,
      unitType: '1_request',
      metadata: { provider: 'together', model: 'llama-4-maverick', baseCost: 0.0004 },
    },
    {
      itemCode: 'TEXT_DEEPSEEK_R1',
      category: 'TEXT',
      name: 'DeepSeek R1',
      description: 'DeepSeek reasoning model (~$0.002/req)',
      creditsPerUnit: 4,
      unitType: '1_request',
      metadata: { provider: 'together', model: 'deepseek-r1', baseCost: 0.002 },
    },
    {
      itemCode: 'TEXT_GEMINI_PRO',
      category: 'TEXT',
      name: 'Gemini Pro',
      description: 'Google Gemini 2.5 Pro — premium quality (~$0.003/req)',
      creditsPerUnit: 4,
      unitType: '1_request',
      metadata: { provider: 'google', model: 'gemini-2.5-pro', baseCost: 0.003 },
    },
    {
      itemCode: 'TEXT_GPT4O',
      category: 'TEXT',
      name: 'GPT-4o',
      description: 'Most advanced OpenAI model (~$0.003/req)',
      creditsPerUnit: 5,
      unitType: '1_request',
      metadata: { provider: 'openai', model: 'gpt-4o', baseCost: 0.003 },
    },
    {
      itemCode: 'TEXT_CLAUDE_SONNET',
      category: 'TEXT',
      name: 'Claude Sonnet 4',
      description: 'Anthropic Claude Sonnet 4 (~$0.005/req)',
      creditsPerUnit: 5,
      unitType: '1_request',
      metadata: { provider: 'anthropic', model: 'claude-sonnet-4-20250514', baseCost: 0.005 },
    },

    // ═══════════════════════════════════════════════════
    // IMAGE MODELS (sorted by credits/cost)
    // ═══════════════════════════════════════════════════
    {
      itemCode: 'IMAGE_FLUX_SCHNELL',
      category: 'IMAGE',
      name: 'Flux Schnell',
      description: 'Ultra-fast affordable images via Runware ($0.0006/img)',
      creditsPerUnit: 1,
      unitType: '1_image',
      metadata: { provider: 'runware', model: 'flux-schnell', baseCost: 0.0006 },
    },
    {
      itemCode: 'IMAGE_SDXL_LIGHTNING',
      category: 'IMAGE',
      name: 'SDXL Lightning',
      description: 'Ultra-fast 4-step generation via Runware ($0.0006/img)',
      creditsPerUnit: 1,
      unitType: '1_image',
      metadata: { provider: 'runware', model: 'sdxl-lightning', baseCost: 0.0006 },
    },
    {
      itemCode: 'IMAGE_SDXL',
      category: 'IMAGE',
      name: 'Stable Diffusion XL',
      description: 'High-quality versatile generation via Runware ($0.0026/img)',
      creditsPerUnit: 2,
      unitType: '1_image',
      metadata: { provider: 'runware', model: 'sdxl', baseCost: 0.0026 },
    },
    {
      itemCode: 'IMAGE_FLUX_2_TURBO',
      category: 'IMAGE',
      name: 'Flux 2 Turbo',
      description: 'New fast Flux model via Fal.ai ($0.008/img)',
      creditsPerUnit: 3,
      unitType: '1_image',
      metadata: { provider: 'fal', model: 'flux-2-turbo', baseCost: 0.008 },
    },
    {
      itemCode: 'IMAGE_PLAYGROUND',
      category: 'IMAGE',
      name: 'Playground v2.5',
      description: 'Aesthetic high-quality images (~$0.01/img)',
      creditsPerUnit: 3,
      unitType: '1_image',
      metadata: { provider: 'replicate', model: 'playground-v2-5', baseCost: 0.01 },
    },
    {
      itemCode: 'IMAGE_FLUX_DEV',
      category: 'IMAGE',
      name: 'Flux Dev',
      description: 'High-quality Flux generation via Runware ($0.0038/img)',
      creditsPerUnit: 5,
      unitType: '1_image',
      metadata: { provider: 'runware', model: 'flux-dev', baseCost: 0.0038 },
    },
    {
      itemCode: 'IMAGE_FLUX_KONTEXT',
      category: 'IMAGE',
      name: 'Flux Kontext Pro',
      description: 'Context-aware image editing via KieAI (~$0.01/img)',
      creditsPerUnit: 5,
      unitType: '1_image',
      metadata: { provider: 'kieai', model: 'flux-kontext', baseCost: 0.01 },
    },
    {
      itemCode: 'IMAGE_SEEDREAM',
      category: 'IMAGE',
      name: 'Seedream 4.0',
      description: 'ByteDance Seedream image gen via KieAI (~$0.0175/img)',
      creditsPerUnit: 5,
      unitType: '1_image',
      metadata: { provider: 'kieai', model: 'seedream', baseCost: 0.0175 },
    },
    {
      itemCode: 'IMAGE_NANO_BANANA_PRO',
      category: 'IMAGE',
      name: 'Nano Banana Pro',
      description: 'Gemini-based image generation via KieAI (~$0.02/img)',
      creditsPerUnit: 8,
      unitType: '1_image',
      metadata: { provider: 'kieai', model: 'nano-banana-pro', baseCost: 0.02 },
    },
    {
      itemCode: 'IMAGE_DALLE2',
      category: 'IMAGE',
      name: 'DALL-E 2',
      description: 'OpenAI DALL-E 2 — fast and affordable ($0.02/img)',
      creditsPerUnit: 8,
      unitType: '1_image',
      metadata: { provider: 'openai', model: 'dall-e-2', baseCost: 0.02 },
    },
    {
      itemCode: 'IMAGE_FLUX_PRO',
      category: 'IMAGE',
      name: 'Flux Pro v1.1',
      description: 'Best quality Flux generation (~$0.04/img)',
      creditsPerUnit: 15,
      unitType: '1_image',
      metadata: { provider: 'fal', model: 'flux-pro', baseCost: 0.04 },
    },
    {
      itemCode: 'IMAGE_DALLE3',
      category: 'IMAGE',
      name: 'DALL-E 3',
      description: 'OpenAI premium image generation ($0.04/img)',
      creditsPerUnit: 20,
      unitType: '1_image',
      metadata: { provider: 'openai', model: 'dall-e-3', baseCost: 0.04 },
    },
    {
      itemCode: 'IMAGE_MIDJOURNEY',
      category: 'IMAGE',
      name: 'Midjourney',
      description: 'Midjourney artistic image generation via KieAI (~$0.04/img)',
      creditsPerUnit: 20,
      unitType: '1_image',
      metadata: { provider: 'kieai', model: 'midjourney', baseCost: 0.04 },
    },

    // ═══════════════════════════════════════════════════
    // VIDEO MODELS (sorted by credits/cost)
    // ═══════════════════════════════════════════════════
    {
      itemCode: 'VIDEO_WAN',
      category: 'VIDEO',
      name: 'Wan 2.5',
      description: 'Wan AI video generation via Fal.ai (~$0.25/5s)',
      creditsPerUnit: 10,
      unitType: '1_video',
      minCredits: 10,
      maxCredits: 15,
      metadata: { provider: 'fal', model: 'wan', baseCost: 0.25 },
    },
    {
      itemCode: 'VIDEO_SEEDANCE',
      category: 'VIDEO',
      name: 'Seedance 1.5',
      description: 'ByteDance Seedance 1.5 Pro via KieAI (~$0.20/video)',
      creditsPerUnit: 10,
      unitType: '1_video',
      minCredits: 10,
      maxCredits: 15,
      metadata: { provider: 'kieai', model: 'seedance', baseCost: 0.20 },
    },
    {
      itemCode: 'VIDEO_KLING',
      category: 'VIDEO',
      name: 'Kling Standard (5s)',
      description: 'Kling 5-second video via PiAPI (~$0.26)',
      creditsPerUnit: 12,
      unitType: '1_video',
      minCredits: 12,
      maxCredits: 18,
      metadata: { provider: 'piapi', model: 'kling', baseCost: 0.26 },
    },
    {
      itemCode: 'VIDEO_RUNWAY',
      category: 'VIDEO',
      name: 'Runway Gen-3',
      description: 'Runway video generation via KieAI (~$0.30/video)',
      creditsPerUnit: 15,
      unitType: '1_video',
      minCredits: 15,
      maxCredits: 22,
      metadata: { provider: 'kieai', model: 'runway', baseCost: 0.30 },
    },
    {
      itemCode: 'VIDEO_LUMA',
      category: 'VIDEO',
      name: 'Luma Dream Machine',
      description: 'Luma AI Dream Machine via Fal.ai (~$0.40/5s)',
      creditsPerUnit: 18,
      unitType: '1_video',
      minCredits: 15,
      maxCredits: 25,
      metadata: { provider: 'fal', model: 'luma', baseCost: 0.40 },
    },
    {
      itemCode: 'VIDEO_KLING_PRO',
      category: 'VIDEO',
      name: 'Kling Pro (10s)',
      description: 'Kling 10-second extended video via PiAPI (~$0.46)',
      creditsPerUnit: 20,
      unitType: '1_video',
      minCredits: 18,
      maxCredits: 30,
      metadata: { provider: 'piapi', model: 'kling-pro', baseCost: 0.46 },
    },
    {
      itemCode: 'VIDEO_VEO_FAST',
      category: 'VIDEO',
      name: 'Veo 3 Fast',
      description: 'Google Veo 3 fast mode via KieAI (~$0.40/video)',
      creditsPerUnit: 20,
      unitType: '1_video',
      minCredits: 18,
      maxCredits: 30,
      metadata: { provider: 'kieai', model: 'veo-fast', baseCost: 0.40 },
    },
    {
      itemCode: 'VIDEO_SORA',
      category: 'VIDEO',
      name: 'Sora 2',
      description: 'OpenAI Sora 2 video via KieAI (~$0.50/video)',
      creditsPerUnit: 25,
      unitType: '1_video',
      minCredits: 22,
      maxCredits: 35,
      metadata: { provider: 'kieai', model: 'sora', baseCost: 0.50 },
    },
    {
      itemCode: 'VIDEO_KLING_MASTER',
      category: 'VIDEO',
      name: 'Kling Master (5s)',
      description: 'Kling master quality video via PiAPI (~$0.96)',
      creditsPerUnit: 50,
      unitType: '1_video',
      minCredits: 40,
      maxCredits: 70,
      metadata: { provider: 'piapi', model: 'kling-master', baseCost: 0.96 },
    },
    {
      itemCode: 'VIDEO_VEO',
      category: 'VIDEO',
      name: 'Veo 3 Quality',
      description: 'Google Veo 3 quality mode via KieAI (~$2.00/video)',
      creditsPerUnit: 80,
      unitType: '1_video',
      minCredits: 70,
      maxCredits: 100,
      metadata: { provider: 'kieai', model: 'veo', baseCost: 2.00 },
    },

    // ═══════════════════════════════════════════════════
    // AUDIO MODELS (sorted by credits/cost)
    // ═══════════════════════════════════════════════════
    {
      itemCode: 'AUDIO_DEEPGRAM',
      category: 'AUDIO',
      name: 'Deepgram TTS',
      description: 'Ultra-cheap text-to-speech (~$0.001/req)',
      creditsPerUnit: 1,
      unitType: '1_request',
      metadata: { provider: 'openai', model: 'deepgram-tts', baseCost: 0.001 },
    },
    {
      itemCode: 'AUDIO_WHISPER',
      category: 'AUDIO',
      name: 'Whisper STT',
      description: 'Speech-to-text transcription via Groq (~$0.001/30s)',
      creditsPerUnit: 3,
      unitType: '1_request',
      metadata: { provider: 'groq', model: 'whisper', baseCost: 0.001 },
    },
    {
      itemCode: 'AUDIO_OPENAI_TTS',
      category: 'AUDIO',
      name: 'OpenAI TTS',
      description: 'OpenAI text-to-speech (~$0.003/req)',
      creditsPerUnit: 3,
      unitType: '1_request',
      metadata: { provider: 'openai', model: 'openai-tts', baseCost: 0.003 },
    },
    {
      itemCode: 'AUDIO_FISH_SPEECH',
      category: 'AUDIO',
      name: 'Fish Speech',
      description: 'Fast voice cloning (~$0.03/req)',
      creditsPerUnit: 5,
      unitType: '1_request',
      metadata: { provider: 'replicate', model: 'fish-speech', baseCost: 0.03 },
    },
    {
      itemCode: 'AUDIO_XTTS',
      category: 'AUDIO',
      name: 'XTTS v2',
      description: 'Multilingual voice cloning (~$0.05/req)',
      creditsPerUnit: 8,
      unitType: '1_request',
      metadata: { provider: 'replicate', model: 'xtts-v2', baseCost: 0.05 },
    },
    {
      itemCode: 'AUDIO_BARK',
      category: 'AUDIO',
      name: 'Bark',
      description: 'Text-to-speech with emotion (~$0.07/req)',
      creditsPerUnit: 8,
      unitType: '1_request',
      metadata: { provider: 'replicate', model: 'bark', baseCost: 0.07 },
    },
    {
      itemCode: 'AUDIO_ELEVENLABS',
      category: 'AUDIO',
      name: 'ElevenLabs TTS',
      description: 'Premium text-to-speech (~$0.06/req)',
      creditsPerUnit: 12,
      unitType: '1_request',
      metadata: { provider: 'elevenlabs', baseCost: 0.06 },
    },
    {
      itemCode: 'AUDIO_SUNO',
      category: 'AUDIO',
      name: 'Suno AI Music',
      description: 'AI music generation (~$0.10/song)',
      creditsPerUnit: 60,
      unitType: '1_song',
      metadata: { provider: 'replicate', model: 'suno', baseCost: 0.10 },
    },
  ];

  for (const price of prices) {
    await prisma.priceItem.upsert({
      where: { itemCode: price.itemCode },
      create: price,
      update: price,
    });
  }

  console.log(`Seeded ${prices.length} price items`);
}

seedPrices()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
